<script setup lang="ts">
import type { HistoryAnalytics, ShiftReport, WorkerRating } from '../api'
import MetricCard from './MetricCard.vue'

defineProps<{ shift?: ShiftReport; workers?: WorkerRating[]; history?: HistoryAnalytics }>()
</script>

<template>
  <div class="page-heading"><div><div class="eyebrow">Аналитика производства</div><h1>Результаты смены</h1><p>Показатели рассчитаны по неизменяемому журналу событий</p></div></div>
  <div class="metrics-grid"><MetricCard label="Выдано" :value="shift?.issued??0" icon="assignment" tone="blue"/><MetricCard label="Выполнено" :value="shift?.completed??0" icon="task_alt" tone="green"/><MetricCard label="В работе" :value="shift?.active??0" icon="construction" tone="amber"/><MetricCard label="Просрочено" :value="shift?.overdue??0" icon="alarm" tone="red"/></div>
  <section class="report-grid">
    <q-card flat bordered class="report-card rating-card"><q-card-section class="card-heading"><div><h2>Рейтинг исполнителей</h2><p>Качество · сроки · надёжность · объём · дисциплина</p></div><q-icon name="leaderboard"/></q-card-section><q-separator/><q-list separator><q-item v-for="(worker,index) in workers" :key="worker.worker_id" class="worker-row"><q-item-section avatar><q-avatar :class="['rank',{'rank-first':index===0&&worker.score>0}]">{{ index+1 }}</q-avatar></q-item-section><q-item-section><q-item-label class="worker-name">{{ worker.full_name }}</q-item-label><q-item-label caption>{{ worker.specialty }} · {{ worker.completed }} из {{ worker.assigned }} выполнено</q-item-label><q-linear-progress rounded size="6px" :value="worker.score/100" color="primary" track-color="grey-3" class="q-mt-sm"/></q-item-section><q-item-section side><div class="score">{{ worker.score }}</div><small>из 100</small></q-item-section></q-item></q-list></q-card>
    <q-card flat bordered class="report-card summary-card"><q-card-section class="card-heading"><div><h2>Показатели</h2><p>Оперативная сводка</p></div><q-icon name="query_stats"/></q-card-section><q-card-section class="summary-list"><div><span>Среднее время реакции</span><b>{{ shift?.average_response_minutes??'—' }} мин</b></div><div><span>Отклонено исполнителями</span><b>{{ shift?.rejected??0 }}</b></div><div><span>Закрыто мастером</span><b>{{ shift?.closed??0 }}</b></div></q-card-section></q-card>
  </section>
  <div class="section-title"><div class="eyebrow">История за 90 дней</div><h2>Выявленные закономерности</h2><p>Проанализировано {{ history?.orders_analyzed??0 }} нарядов</p></div>
  <div class="patterns-grid"><article v-for="pattern in history?.patterns" :key="pattern.kind" :class="['pattern',`severity-${pattern.severity}`]"><div class="pattern-icon"><q-icon :name="pattern.kind==='problem_equipment'?'precision_manufacturing':pattern.kind==='repeated_fault'?'repeat':'inventory_2'"/></div><div><h3>{{ pattern.title }}</h3><p>{{ pattern.evidence }}</p><div class="recommendation"><b>Рекомендация</b>{{ pattern.recommendation }}</div></div></article></div>
  <section class="report-grid bottom-grid"><q-card flat bordered class="report-card"><q-card-section class="card-heading"><div><h2>Проблемное оборудование</h2><p>Лидеры по внеплановым отказам</p></div><q-icon name="warning_amber"/></q-card-section><q-markup-table flat><thead><tr><th class="text-left">Оборудование</th><th class="text-right">Отказы</th><th class="text-right">Простой</th></tr></thead><tbody><tr v-for="item in history?.top_equipment.slice(0,5)" :key="item.equipment_id"><td>{{ item.name }}</td><td class="text-right text-weight-bold">{{ item.unplanned_failures }}</td><td class="text-right">{{ item.downtime_hours }} ч</td></tr></tbody></q-markup-table></q-card><q-card flat bordered class="report-card"><q-card-section class="card-heading"><div><h2>Аномальные списания</h2><p>Отклонение от среднего расхода</p></div><q-icon name="inventory_2"/></q-card-section><q-list separator><q-item v-for="item in history?.material_anomalies.slice(0,6)" :key="`${item.work_order}-${item.material}`"><q-item-section><q-item-label>{{ item.work_order }} · {{ item.material }}</q-item-label><q-item-label caption>Норма {{ item.average }}, списано {{ item.quantity }}</q-item-label></q-item-section><q-item-section side><q-badge color="negative">×{{ item.deviation_factor }}</q-badge></q-item-section></q-item><q-item v-if="!history?.material_anomalies.length"><q-item-section class="text-grey-6">Аномалий не обнаружено</q-item-section></q-item></q-list></q-card></section>
</template>

<style scoped>
.page-heading{margin-bottom:28px}.eyebrow{text-transform:uppercase;letter-spacing:.14em;color:#34805e;font-size:10px;font-weight:800}.page-heading h1{font-size:34px;letter-spacing:-.035em;margin:7px 0 5px}.page-heading p,.section-title p{margin:0;color:#748079;font-size:13px}.metrics-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-bottom:24px}.report-grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(280px,1fr);gap:16px}.report-card{border-radius:16px;border-color:#dfe7e3;box-shadow:0 3px 12px rgb(20 52 40/4%)}.card-heading{display:flex;justify-content:space-between;align-items:center;padding:20px 22px}.card-heading h2{font-size:17px;margin:0}.card-heading p{font-size:10px;color:#85918b;margin:4px 0 0}.card-heading>.q-icon{font-size:28px;color:#80a493}.worker-row{padding:13px 18px}.worker-name{font-weight:700}.rank{background:#eef2f0;color:#65736c;font-size:12px}.rank-first{background:#f5d66e;color:#644a00}.score{font-size:20px;font-weight:800;color:#176b47}.worker-row small{font-size:8px;color:#8b9691}.summary-list{padding:6px 22px 18px}.summary-list>div{display:flex;justify-content:space-between;align-items:center;padding:17px 0;border-bottom:1px solid #edf1ef;color:#6d7b74;font-size:11px}.summary-list>div:last-child{border:0}.summary-list b{font-size:16px;color:#24332c}.section-title{margin:36px 0 15px}.section-title h2{font-size:22px;margin:6px 0 3px}.patterns-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.pattern{display:flex;gap:14px;padding:20px;background:#fff;border:1px solid #dfe7e3;border-top:3px solid #dfa529;border-radius:14px}.pattern.severity-high{border-top-color:#c4433a}.pattern-icon{flex:0 0 38px;height:38px;display:grid;place-items:center;border-radius:10px;background:#f2f5f3;color:#47725e;font-size:22px}.pattern h3{font-size:14px;margin:1px 0 8px}.pattern p{font-size:11px;line-height:1.5;color:#66746d}.recommendation{padding-top:10px;border-top:1px solid #edf1ef;font-size:10px;color:#52625a}.recommendation b{display:block;color:#2f493c;margin-bottom:3px}.bottom-grid{margin-top:16px;grid-template-columns:1fr 1fr}@media(max-width:1200px){.metrics-grid{grid-template-columns:repeat(2,1fr)}.patterns-grid{grid-template-columns:1fr}.report-grid{grid-template-columns:1fr}}@media(max-width:599px){.page-heading h1{font-size:28px}.metrics-grid{grid-template-columns:repeat(2,1fr);gap:9px}.worker-row{padding:12px}.score{font-size:17px}}
</style>
